# Generated by Django 5.2.8 on 2026-05-13 19:30

from django.db import migrations, models
from django.utils import timezone


def backfill_published_on(apps, schema_editor):
    Article = apps.get_model("worldjungletales", "Article")
    Article.objects.filter(status=1, published_on__isnull=True).update(
        published_on=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('worldjungletales', '0003_alter_subscriber_author_articleview'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('feature', 'Feature'), ('dispatch', 'Field Dispatch'), ('guide', 'Guide'), ('interview', 'Interview'), ('photo_essay', 'Photo Essay'), ('news', 'News'), ('profile', 'Species Profile')], default='feature', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='author_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='editor_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='hero_priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='image_credit',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='article',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_published_on, migrations.RunPython.noop),
    ]
